entry='''## 0.12.8 - 2026-09-03 — engine fixes in-tree: icons, contrast, text wrap, form boxes
- **Servo + Stylo are now vendored and patched** (`vendor/servo`, `vendor/stylo`, wired with `[patch]` in Cargo.toml; base revs in `UPSTREAM_REV`). Site problems get fixed in the engine from here on.
- **Dropped CSS:** `:has()` enabled (223 rules were dropped on a 6-site run, now 0); `@media` features prefers-reduced-motion / prefers-reduced-transparency / prefers-contrast / forced-colors / inverted-colors / dynamic-range / -ms-high-contrast evaluate (507 dropped media blocks -> 0); `text-wrap`, `word-break: break-word`, `display: -webkit-box` parse.
- **Icons:** `mask-image: url()` paints (mask image tinted with the background colour through a WebRender colour matrix; gradient masks paint nothing instead of a solid box); inline SVG `fill="color(display-p3 …)"` from the repair script is converted to `rgb()` so wordmarks like speedtest's show; WOFF2 icon fonts verified (Material Icons, Font Awesome).
- **Contrast:** `-webkit-text-fill-color` paints; `background-clip: text` no longer draws the gradient as a box and transparent-fill text takes the first gradient stop.
- **Text wrap:** `overflow-wrap: break-word|anywhere` and `word-break: break-word` break long tokens (URLs) only when the word is wider than the line, Chrome-style.
- **Form boxes:** `<textarea rows>` height is rows x 1.25em (was rows x 1em, cropping the second line).
- **Site JS:** document-start polyfill via Servo user scripts: `requestIdleCallback`/`cancelIdleCallback` (GitHub's React partials threw and rendered "Looks like something went wrong"), `scrollIntoViewIfNeeded`.
- **Desktop:** window position + maximized state persist and restore clamped to the monitor work area (was landing under the taskbar / half off-screen); window title follows tab switches; key release after a consumed shortcut (Ctrl+digit, Ctrl+Tab) no longer leaks into the page; local `file://` pages can load their own subresources.
- Debug: `AMNI_TRACE_INPUT=1`, `AMNI_PROBE_JS=<file>`, `scripts/probe_sites.ps1`, `test/engine/features.html`.
- Known: `-webkit-line-clamp` still gecko-only; gradient masks (gradient border rings) paint nothing; 3 pre-existing unit tests fail on the uncommitted 0.12.7 chrome (anchor 119px chrome, compat sheet font-stretch).

'''
p='CHANGELOG.md'; s=open(p,encoding='utf-8').read(); open(p,'w',encoding='utf-8').write(entry+s)
arch='''## 2026-09-03 v0.12.8 engine in-tree (vendor/servo + vendor/stylo)
- **Law:** site glitches that trace to the engine get fixed in `vendor/servo` / `vendor/stylo` (copies of servo c91fc17 / stylo b3e6425, `[patch]` in Cargo.toml; `scripts/gen_servo_patch.py` regenerates the 59-crate servo table; the patch key must be the `.git` URL used by the dependency). Stylo atoms for new media features live in `vendor/stylo/stylo_atoms/static_atoms.txt`.
- **Stylo prefs** that Servo never wires: `stylo_static_prefs::set_pref!` in `servo_prefs()` (has-selector, nth-child-of, starting-style, light-dark images).
- **Servo layout patches:** `display_list/mod.rs` text path paints `-webkit-text-fill-color` (falls back to `background::representative_color` when clip is text); `background-clip: text` layers skipped; `mask_image_layer` + `background::layout_mask` resolve `mask-image: url()` and paint it through `FilterOp::ColorMatrix` tint (WebRender 0.70 image-mask clips panic on rect primitives and paint nothing on pictures); gradient masks return a DUMMY key so the box is not painted. `flow/inline`: `WordFragment` slices + `process_weak_wrap_opportunity` implement emergency breaking; `style_ext.rs` maps `-webkit-box` to flex. `script/dom/element`: textarea rows -> 1.25em each.
- **User scripts:** `AppState.user_content` (Servo `UserContentManager`) injects `servo_compat::document_start_script()` before page scripts on every content webview (requestIdleCallback, scrollIntoViewIfNeeded).
- **Desktop:** `restore_window_position` (windows-sys `MonitorFromPoint`/`GetMonitorInfoW` work area) + `window_x/window_y/maximized` in session.json; `shortcut_keys` swallows releases of consumed shortcut keys; `sync_window_title` on switch_tab; `file_subresource_allowed` admits local subresources when the document is unknown (referrer is stripped for file: documents).
- **Gates:** `scripts/check.cmd` (~3 min), `scripts/build_release.cmd` (10-14 min), `scripts/probe_sites.ps1 -Urls @(...)` via `powershell -Command` (window picked by PID + area; probe output travels through `document.title`), `test/engine/features.html` + `probe_dom.js` / `probe_text.js`.
'''
p='architecture_map.md'; s=open(p,encoding='utf-8').read(); open(p,'w',encoding='utf-8').write(arch+s)
p='docs/checklists/checklist_engine_fixes_v0.12.8.md'; s=open(p,encoding='utf-8').read()
s=s.replace('- [ ] `fill: GrayText` system colors in SVG paint','- [ ] `fill: GrayText` system colors in SVG paint (4 occurrences, deferred)')
s=s.replace('- [ ] Release build green + on-screen check of test/engine/features.html','- [x] Release build green + on-screen check of test/engine/features.html (mask icons, icon fonts, gradient text, :has, media features, break-word, URL wrap, -webkit-box)\n- [x] mask-image via WebRender image-mask clip panicked on rects and painted nothing on pictures; replaced by ColorMatrix tint of the mask image\n- [x] Gradient masks: paint nothing (no solid box)\n- [x] SVG repair: `color(display-p3 …)` -> rgb() (speedtest wordmark visible)\n- [x] textarea rows x 1.25em (lh unit resolved to ~0 in Servo)\n- [x] requestIdleCallback polyfill as a document-start user script (GitHub error banner)')
s=s.replace('- [ ] Speedtest wordmark missing','- [x] Speedtest wordmark missing (p3 fill)')
s=s.replace('- [ ] cargo check clean','- [x] cargo check clean; cargo test 197 pass / 3 pre-existing failures (anchor 119px chrome, compat sheet font-stretch) untouched by this lap')
s=s.replace('- [ ] architecture_map.md + changelog.md entries','- [x] architecture_map.md + CHANGELOG.md entries\n- [ ] Anthony confirms on his sites')
open(p,'w',encoding='utf-8').write(s)
p=r'C:\Users\antho\.claude\projects\C--Users-antho-Documents-ai\memory\project_amni_browse_vendored_engine.md'; s=open(p,encoding='utf-8').read()
s=s.replace('**WebRender gotcha:**','**WebRender gotchas:** image-mask clips (`define_clip_image_mask`) panic on rect primitives ("image-masks not expected on rect/quads") and painted NOTHING when applied to a stacking context; `mask-image` is painted as the mask image itself through `FilterOp::ColorMatrix` (column-major 4x4 + offset; alpha column carries bg alpha, offset carries bg rgb). Also:')
s+='\n**Other engine facts (2026-09-03):** Servo has no emergency mid-word breaking; `WordFragment` slices + `process_weak_wrap_opportunity` add it. `lh` unit resolves to ~0 in Servo (textarea rows uses 1.25em). Servo lacks `requestIdleCallback`; polyfilled via `UserContentManager` user script at document start (GitHub React partials need it). Referrer is stripped for file: documents, so the file:// subresource gate must not rely on it. WOFF2 works (fontsan wuff). Window title must be re-synced on tab switch.\n'
open(p,'w',encoding='utf-8').write(s)
print('docs+memory ok')
